FROM node:18-alpine as build-stage

WORKDIR /app
RUN corepack enable
RUN corepack prepare pnpm@8.6.10 --activate

RUN npm config set registry https://registry.npmmirror.com

COPY .npmrc package.json ./
RUN pnpm install

CMD ["pnpm", "run", "build"]
